version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=weesu_db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weesu_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
